# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6
        - python3

# Set the build environment
env:
    - SMVERSION=1.8 CACHE_BUILDER=tf2idb
    - SMVERSION=1.8 CACHE_BUILDER=tf2ii
    - SMVERSION=1.9 CACHE_BUILDER=tf2idb
    - SMVERSION=1.9 CACHE_BUILDER=tf2ii

# Allow the experimental branch to fail
matrix:
    fast_finish: true
    allow_failures:
        - env: SMVERSION=1.9

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - COMPILE_SOURCEMOD_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod"
    - COMPILE_SCRIPTING_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod/scripting"
    - wget https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2items.inc
    - wget https://raw.githubusercontent.com/chauffer/tf2itemsinfo/master/scripting/include/tf2itemsinfo.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2itemsinfo.inc
    - wget https://raw.githubusercontent.com/FlaminSarge/tf2idb/master/scripting/include/tf2idb.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2idb.inc
    - AVERSIONING_COMMIT=$(git rev-list --count HEAD)

before_script:
    - python3 "$TRAVIS_BUILD_DIR/.buildtools/versioning/versioner.py" "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR/scripting/include/tf2_taunts_tf2idb" "$TRAVIS_TAG"
    - chmod +x "$COMPILE_SCRIPTING_FOLDER/spcomp"
    - cp -r "$TRAVIS_BUILD_DIR/scripting" "$COMPILE_SOURCEMOD_FOLDER"
    - mkdir "$TRAVIS_BUILD_DIR/plugins"
    - FILE=tf2_taunts_tf2idb-n$AVERSIONING_COMMIT-$CACHE_BUILDER.zip
    - if [ "$CACHE_BUILDER" = "tf2ii" ]; then EXTRA_ARGS='_USE_TF2II_INSTEAD_OF_TF2IDB='; else EXTRA_ARGS=''; fi

# And compile!
script: 
    - $COMPILE_SCRIPTING_FOLDER/spcomp $COMPILE_SCRIPTING_FOLDER/tf2_taunts_tf2idb.sp -o$TRAVIS_BUILD_DIR/plugins/tf2_taunts_tf2idb.smx $EXTRA_ARGS

before_deploy:
    - zip -r $FILE ./translations/ ./plugins/ ./scripting/ ./gamedata/

deploy:
    provider: releases
    api_key:
        secure: cfmiJb0kZfusm8RU2CJmKvDQPByXPqA1YxKeGCOnJlXY55pvJwMB+iqGW5zmxAOfv4x9H4LAdUstc7TOnGtw06hqrOEPsUTIo58uZqnZbNI6VyhMajdTHrLe/FPLeUbPu4f4AVU9KuSgi/td+6yzXuyQ4ZjFJoZYwBWKAmNGKEv2QQgSIKA0/BxsAfSQEHkwJd27HrRjwWdvCIF7oEDf2TAFdYOt9CvAgj7ARsW4st6z7aRf9TmGb3yEUkTm3JkU/LIVK6t77+o4X7MVorgDD6f7QWIzyjVFg/A9tkYOK/xIn2TXj82y2cvEzQGT9aKsHWt/IHWnSJej6DvBwP+dZEVGQHvVn2GfEJXAyrT+jacPWpbC8FOddiw/SSQFfACI8s6F52koNpSDxJmeihPc0Kynk46o/fed/Vg5Mb+hKl8CNJvee5Izsxty+mYVQoK+aHrXZPyPbm4WbeL+chGoU3O36VbFvTXMA5fN+Ot4vwGsxutXbImva8IHYmW5LNT+2d1Z57sbGf0bgEjeozE8shHHQwHECVLRGIXmzYtoWFjvtmLbt2CC9vYjooKjQv7+wjGSrya2u61rWC8w2BaJnzdguXroU+0TaIdzdDrC85r9VttcvEOWNLROTf+7Fgxq/dAyvfyz3pw2Noh8zyr3RUrXfLWhCLagLoeZ93agNUY=
    file: $FILE
    skip_cleanup: true
    on:
        #only deploy for the stable branch
        condition: $SMVERSION = 1.8
        repo: fakuivan/TF2-Taunts-TF2IDB
        tags: true

# Notifications
notifications:
    email: false
