# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6
        - python3

# Set the build environment
env:
    - SMVERSION=1.8 CACHE_BUILDER=tf2idb
    - SMVERSION=1.8 CACHE_BUILDER=tf2ii
    - SMVERSION=1.9 CACHE_BUILDER=tf2idb
    - SMVERSION=1.9 CACHE_BUILDER=tf2ii

# Allow the experimental branch to fail
matrix:
    fast_finish: true
    allow_failures:
        - env: SMVERSION=1.9

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - COMPILE_SOURCEMOD_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod"
    - COMPILE_SCRIPTING_FOLDER="$TRAVIS_BUILD_DIR/addons/sourcemod/scripting"
    - wget https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2items.inc
    - wget https://raw.githubusercontent.com/chauffer/tf2itemsinfo/master/scripting/include/tf2itemsinfo.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2itemsinfo.inc
    - wget https://raw.githubusercontent.com/FlaminSarge/tf2idb/master/scripting/include/tf2idb.inc -O $COMPILE_SCRIPTING_FOLDER/include/tf2idb.inc
    - AVERSIONING_COMMIT=$(git rev-list --count HEAD)

before_script:
    - python3 "$TRAVIS_BUILD_DIR/.buildtools/versioner.py" "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR/scripting/include/tf2_taunts_tf2idb" "$TRAVIS_TAG"
    - chmod +x "$COMPILE_SCRIPTING_FOLDER/spcomp"
    - cp -r "$TRAVIS_BUILD_DIR/scripting" "$COMPILE_SOURCEMOD_FOLDER"
    - mkdir "$TRAVIS_BUILD_DIR/plugins"
    - FILE=tf2_taunts_tf2idb-n$AVERSIONING_COMMIT-$CACHE_BUILDER.zip
    - if [ "$CACHE_BUILDER" = "tf2ii" ]; then EXTRA_ARGS='_USE_TF2II_INSTEAD_OF_TF2IDB='; else EXTRA_ARGS=''; fi

# And compile!
script: 
    - $COMPILE_SCRIPTING_FOLDER/spcomp $COMPILE_SCRIPTING_FOLDER/tf2_taunts_tf2idb.sp -o$TRAVIS_BUILD_DIR/plugins/tf2_taunts_tf2idb.smx $EXTRA_ARGS

before_deploy:
    - zip -r $FILE $TRAVIS_BUILD_DIR/translations/ $TRAVIS_BUILD_DIR/plugins/ $TRAVIS_BUILD_DIR/scripting/ $TRAVIS_BUILD_DIR/gamedata/

deploy:
    provider: releases
    api_key:
        secure: 
    file: $FILE
    skip_cleanup: true
    on:
        repo: fakuivan/TF2-Taunts-TF2IDB
        tags: true

# Notifications
notifications:
    email: false
